-- ===========================================================
-- Infarm CS — pulihkan aturan pemicu dari berkas .md
--
-- Isi: 43 aturan. TIDAK menyentuh tabel templates,
-- jadi perbaikan kalimat yang sudah ditulis tim CS tetap utuh.
--
-- Kapan dipakai: bila `npm run periksa-aturan` melaporkan ada
-- aturan yang menyimpang dari berkas — biasanya karena `also`
-- atau `unless` hilang saat template disimpan lewat halaman.
--
-- Cara pakai: SQL Editor -> tempel seluruh isi -> Run
-- Sifat     : idempoten, aman dijalankan berulang kali.
-- ===========================================================

begin;

-- Aturan lama DIHAPUS, bukan sekadar dinonaktifkan.
--
-- Menonaktifkan terasa lebih hati-hati dan justru tidak bisa:
-- `priority` punya batasan UNIQUE yang berlaku untuk SEMUA baris,
-- aktif maupun tidak. Baris mati bernomor 37 tetap memblokir
-- aturan baru bernomor 37, dan seluruh transaksi ini akan gagal.
--
-- Menghapus aman di sini karena aturan pemicu adalah data turunan
-- dari berkas .md — bisa dibangkitkan ulang kapan saja lewat
-- `npm run template-sql`. Yang benar-benar butuh jejak adalah ISI
-- template (dosis), dan itu disimpan terpisah di
-- template_revisions oleh trigger, tidak tersentuh berkas ini.
--
-- ⚠️  Perubahan kata kunci yang ditulis tim CS lewat halaman Kelola
-- Template IKUT tergantikan versi dari berkas .md. Itu memang
-- maksudnya: berkas ini untuk memulihkan aturan yang rusak.
delete from public.template_rules;

insert into public.template_rules
  (template_id, priority, when_patterns, also_pattern, unless_patterns, why)
select t.id, v.priority, v.when_patterns, v.also_pattern, v.unless_patterns, v.why
from (values
  ('BANTU', 1, ARRAY['^\s*(halo|hallo|hai|hay|hi|hello|pagi|siang|sore|malam|permisi|assalamualaikum|assalamu''alaikum)(\s+(kak|ka|kk|min|minfarm|admin|bang|sis))?[\s\p{P}\p{S}]*$', '^\s*(min|kak|kk|admin|minfarm)[\s\p{P}\p{S}]*$']::text[], NULL, '{}'::text[], 'Sapaan tanpa pertanyaan. Balasan pembuka CS memang kalimat tetap.'),
  ('TQ', 2, ARRAY['^\s*(makasih|makasi|mksh|terima ?kasih|thanks|thank you|tq|oke|okey|ok|sip|siap|baik|noted)(\s+(kak|ka|kk|min|minfarm|admin))?[\s\p{P}\p{S}]*$']::text[], NULL, '{}'::text[], 'Ucapan terima kasih. Tidak ada informasi yang perlu dicari.'),
  ('LACAK', 3, ARRAY['\b(lacak|tracking)\b', '\b(posisi|status)\s+(paket|pesanan|barang)\b', '\bpaket\w*\s+(saya|aku|ku)?\s*(sudah )?(sampai )?mana\b', '\bsampai mana\b']::text[], NULL, ARRAY['\b(belum sampai|tidak sampai|hilang|lama|telat|terlambat|refund|komplain)\b']::text[], 'Permintaan cara melacak paket. Balasannya arahan baku ke menu lacak.'),
  ('HARGA', 4, ARRAY['\bharga(nya)?\b', '\bberapa(an)? (harganya|duit|rupiah)\b']::text[], NULL, ARRAY['\b(dosis|takaran|ongkir|ongkos kirim)\b']::text[], 'Pertanyaan harga. Template mengarahkan ke halaman produk tanpa menyebut angka — sesuai larangan sop.md.'),
  ('GARANSI', 5, ARRAY['\bgaransi\b']::text[], NULL, '{}'::text[], 'Syarat garansi adalah kebijakan tetap yang tidak boleh bervariasi.'),
  ('OFFLINE', 6, ARRAY['\b(toko|gerai|outlet)\s*(offline|fisik)\b', '\boffline store\b', '\b(bisa|boleh)\s+(datang|mampir|ke toko)\b']::text[], NULL, '{}'::text[], 'Ketersediaan toko offline adalah fakta tetap.'),
  ('LIBUR', 7, ARRAY['\b(tanggal merah|hari libur|libur nasional)\b']::text[], NULL, '{}'::text[], 'Jadwal operasional hari libur adalah kebijakan tetap.'),
  ('SENIN', 8, ARRAY['\b(sabtu|minggu|weekend|akhir pekan)\b.*\b(kirim|dikirim|proses|diproses)\b', '\b(kirim|dikirim|proses|diproses)\b.*\b(sabtu|minggu|weekend|akhir pekan)\b']::text[], NULL, '{}'::text[], 'Kebijakan pemrosesan pesanan akhir pekan, kalimatnya tetap.'),
  ('PAKAI POC', 9, ARRAY['\b(cara (pakai|penggunaan|pake|aplikasi)|gimana pakai|dosis|takaran)\b.*\bpoc\b', '\bpoc\b.*\b(cara (pakai|penggunaan|pake)|dosis|takaran)\b']::text[], NULL, '{}'::text[], 'Dosis POC wajib persis Knowledge Base — justru berbahaya bila dikarang AI.'),
  ('PAKAI NEEM', 10, ARRAY['\b(cara (pakai|penggunaan|pake)|dosis|takaran)\b.*\b(neem|pestisida)\b', '\b(neem|pestisida)\b.*\b(cara (pakai|penggunaan|pake)|dosis|takaran)\b']::text[], NULL, '{}'::text[], 'Dosis pestisida wajib persis Knowledge Base.'),
  ('PAKAI ABMB', 11, ARRAY['\b(cara (pakai|penggunaan|pake)|dosis|takaran)\b.*\bab ?mix\b', '\bab ?mix\b.*\b(cara (pakai|penggunaan|pake)|dosis|takaran)\b']::text[], NULL, ARRAY['\binstan(t)?\b']::text[], 'Dosis AB Mix wajib persis Knowledge Base, termasuk larangan mencampur stok A dan B.'),
  ('CARA KALIBRASI ULANG TDS METER', 12, ARRAY['\bkalibrasi\b.*\btds\b|\btds\b.*\bkalibrasi\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Prosedur kalibrasi TDS meter — langkah baku, salah urutan bikin alat meleset.'),
  ('CARA KALIBRASI ULANG PH METER', 13, ARRAY['\bkalibrasi\b.*\bph\b|\bph\b.*\bkalibrasi\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Prosedur kalibrasi pH meter — langkah baku.'),
  ('HITUNG PPM TDS', 14, ARRAY['\b(hitung|ngitung|menghitung)\b.*\bppm\b|\bppm\b.*\b(hitung|ngitung|rumus)\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Rumus ppm nutrisi = ppm TDS dikurangi ppm air baku. Angka tetap.'),
  ('CARA PAKAI TDS METER', 15, ARRAY['\btds( ?meter)?\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Langkah pemakaian TDS meter — prosedur baku.'),
  ('CARA PAKAI PH METER', 16, ARRAY['\bph ?meter\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Langkah pemakaian pH meter — prosedur baku.'),
  ('SOIL METER', 17, ARRAY['\bsoil ?meter\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Langkah pemakaian soil meter — prosedur baku.'),
  ('PAKAI ABMC', 18, ARRAY['\bab ?mix instan(t)?\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Dosis AB Mix instan 5 ml A + 5 ml B — wajib persis Knowledge Base.'),
  ('PAKAI FRUITEXPERT', 19, ARRAY['\bfruit ?expert\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Jadwal selang-seling Fruit Expert & POC — aturan tetap, bukan penilaian.'),
  ('VITAMIN AKAR', 20, ARRAY['\bvitamin akar\b|\bvitamin b ?1\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Jadwal selang-seling vitamin akar — aturan tetap.'),
  ('PAKAI AKAR', 21, ARRAY['\b(nutrisi|hormon) akar\b|\bauksin\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Dosis hormon akar 0,5 ml/L untuk stek — wajib persis Knowledge Base.'),
  ('PAKAI B1', 22, ARRAY['\bb ?1\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Dosis B1: 1 tutup botol per 2 liter — wajib persis.'),
  ('MAGNESIUM', 23, ARRAY['\b(magnesium|mgso4|garam inggris)\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Dosis Magnesium Sulfat kocor 5-10 gr/L — wajib persis.'),
  ('CARA PAKAI NPK', 24, ARRAY['\bnpk\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Dosis NPK 1 sdm per liter — wajib persis.'),
  ('PAKAI GUANO', 25, ARRAY['\bguano\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Dosis pupuk guano — wajib persis Knowledge Base.'),
  ('DOLOMIT', 26, ARRAY['\bdolomit\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Dosis dolomit 100-200 gr/m2 — wajib persis.'),
  ('MIRACLE POWDER', 27, ARRAY['\bmiracle( ?powder)?\b|\basam humat\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Dosis Miracle Powder (asam humat) — wajib persis. Ditaruh sebelum [PRODUK MIRACLE] supaya pertanyaan pemakaian tidak dijawab deskripsi.'),
  ('NUTRIPOD', 28, ARRAY['\bnutripod\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Dosis Nutripod 1 sachet per 10 liter — wajib persis.'),
  ('CARA PAKAI ASAM AMINO', 29, ARRAY['\basam amino\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Dosis asam amino 5 ml/L — wajib persis.'),
  ('CARA PAKAI EM4', 30, ARRAY['\bem ?4\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Langkah pengomposan dengan EM4 — prosedur baku.'),
  ('PBM', 31, ARRAY['\bpbm\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Dosis POC Sayur pada paket PBM — wajib persis.'),
  ('PAKAI AGK LENGKAP', 32, ARRAY['\bagk\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Urutan pemakaian paket AGK lengkap — prosedur baku.'),
  ('COCOPEAT', 33, ARRAY['\bcocopeat\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Langkah merendam & memakai cocopeat block — prosedur baku.'),
  ('CANGKOK', 34, ARRAY['\b(cangkok|groot)\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Langkah stek/cangkok dengan groot — prosedur baku.'),
  ('ATRAKTAN PETROGENOL', 35, ARRAY['\b(petrogenol|atraktan)\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Langkah pemasangan perangkap atraktan — prosedur baku.'),
  ('BIVI', 36, ARRAY['\bbivi\b']::text[], '\b(cara (pakai|penggunaan|pake|aplikasi|menggunakan|hitung|menghitung|ngitung|kalibrasi|cangkok|stek|semai|tanam|rendam|merendam)|gimana (cara )?(pakai|pake|makai)|cara nya|caranya|dosis|takaran|kalibrasi|berapa (ml|gram|gr|sendok|sdm|sdt|tutup|sachet)|per liter|per l\b)', '{}'::text[], 'Dosis BIVI 0,5 gr/L pencegahan — wajib persis.'),
  ('PRODUK POC', 37, ARRAY['\bpoc\b']::text[], '\b(apa itu|itu apa|ini apa|apa sih|apaan|fungsi(nya)?|manfaat(nya)?|guna(nya)?|kegunaan(nya)?|kandungan(nya)?|deskripsi(nya)?|singkatan(nya)?|kepanjangan(nya)?|arti(nya)?|maksud(nya)?|jelasin|jelaskan|buat apa|untuk apa|produk apa)\b', ARRAY['\b(cara (pakai|penggunaan|pake|aplikasi)|gimana pakai|dosis|takaran|berapa ml|berapa gram|semprot|siram)\b', '\b(ready|stok|stock|kosong|harga|ongkir|kirim|resi|promo|diskon|garansi)\b']::text[], 'Deskripsi POC: pupuk organik cair untuk melebatkan buah & sayur. Kalimat tetap, tidak bergantung situasi pelanggan.'),
  ('PRODUK MIRACLE', 38, ARRAY['\bmiracle( ?powder)?\b']::text[], '\b(apa itu|itu apa|ini apa|apa sih|apaan|fungsi(nya)?|manfaat(nya)?|guna(nya)?|kegunaan(nya)?|kandungan(nya)?|deskripsi(nya)?|singkatan(nya)?|kepanjangan(nya)?|arti(nya)?|maksud(nya)?|jelasin|jelaskan|buat apa|untuk apa|produk apa)\b', ARRAY['\b(cara (pakai|penggunaan|pake|aplikasi)|gimana pakai|dosis|takaran|berapa ml|berapa gram|semprot|siram)\b', '\b(ready|stok|stock|kosong|harga|ongkir|kirim|resi|promo|diskon|garansi)\b']::text[], 'Deskripsi Miracle Powder: menggemburkan tanah yang mengeras. Kalimat tetap.'),
  ('PRODUK AKAR', 39, ARRAY['\b(produk|nutrisi|booster) akar\b']::text[], '\b(apa itu|itu apa|ini apa|apa sih|apaan|fungsi(nya)?|manfaat(nya)?|guna(nya)?|kegunaan(nya)?|kandungan(nya)?|deskripsi(nya)?|singkatan(nya)?|kepanjangan(nya)?|arti(nya)?|maksud(nya)?|jelasin|jelaskan|buat apa|untuk apa|produk apa)\b', ARRAY['\b(cara (pakai|penggunaan|pake|aplikasi)|gimana pakai|dosis|takaran|berapa ml|berapa gram|semprot|siram)\b', '\b(ready|stok|stock|kosong|harga|ongkir|kirim|resi|promo|diskon|garansi)\b']::text[], 'Deskripsi nutrisi akar: melebatkan akar & mengurangi stres tanaman stek. Kalimat tetap.'),
  ('PRODUK PELEBAT', 40, ARRAY['\b(paket )?pelebat\b']::text[], '\b(apa itu|itu apa|ini apa|apa sih|apaan|fungsi(nya)?|manfaat(nya)?|guna(nya)?|kegunaan(nya)?|kandungan(nya)?|deskripsi(nya)?|singkatan(nya)?|kepanjangan(nya)?|arti(nya)?|maksud(nya)?|jelasin|jelaskan|buat apa|untuk apa|produk apa)\b', ARRAY['\b(cara (pakai|penggunaan|pake|aplikasi)|gimana pakai|dosis|takaran|berapa ml|berapa gram|semprot|siram)\b', '\b(ready|stok|stock|kosong|harga|ongkir|kirim|resi|promo|diskon|garansi)\b']::text[], 'Deskripsi paket pelebat untuk tanaman berbuah. Kalimat tetap.'),
  ('PRODUK PESTISIDA', 41, ARRAY['\bpestisida\b']::text[], '\b(apa itu|itu apa|ini apa|apa sih|apaan|fungsi(nya)?|manfaat(nya)?|guna(nya)?|kegunaan(nya)?|kandungan(nya)?|deskripsi(nya)?|singkatan(nya)?|kepanjangan(nya)?|arti(nya)?|maksud(nya)?|jelasin|jelaskan|buat apa|untuk apa|produk apa)\b', ARRAY['\b(cara (pakai|penggunaan|pake|aplikasi)|gimana pakai|dosis|takaran|berapa ml|berapa gram|semprot|siram)\b', '\b(ready|stok|stock|kosong|harga|ongkir|kirim|resi|promo|diskon|garansi)\b']::text[], 'Deskripsi pestisida organik untuk ulat & kutu. Kalimat tetap; dosisnya tetap milik [PAKAI NEEM] atau AI.'),
  ('PRODUK SEEDBOOSTER', 42, ARRAY['\bseed ?booster\b']::text[], '\b(apa itu|itu apa|ini apa|apa sih|apaan|fungsi(nya)?|manfaat(nya)?|guna(nya)?|kegunaan(nya)?|kandungan(nya)?|deskripsi(nya)?|singkatan(nya)?|kepanjangan(nya)?|arti(nya)?|maksud(nya)?|jelasin|jelaskan|buat apa|untuk apa|produk apa)\b', ARRAY['\b(cara (pakai|penggunaan|pake|aplikasi)|gimana pakai|dosis|takaran|berapa ml|berapa gram|semprot|siram)\b', '\b(ready|stok|stock|kosong|harga|ongkir|kirim|resi|promo|diskon|garansi)\b']::text[], 'Deskripsi seed booster untuk mempercepat benih dorman bertunas. Kalimat tetap.'),
  ('KOMPLAIN', 43, ARRAY['\b(rusak|pecah|bocor|penyok|jamuran|busuk)\b', '\b(salah kirim|kurang|tidak sesuai|gak sesuai|nggak sesuai|beda)\b.*\b(pesanan|barang|isi|produk)\b']::text[], NULL, '{}'::text[], 'Keluhan barang. sop.md mewajibkan alih ke CS manusia — balasan baku justru lebih aman daripada AI menyusun kalimat sendiri.')
) as v(code, priority, when_patterns, also_pattern, unless_patterns, why)
join public.templates t on t.code = v.code;

commit;

-- Periksa sesudahnya, dari folder web/:
--   npm run periksa-aturan
-- Keluarannya harus berbunyi "Semua aturan sepadan".
